#!/bin/bash
# checks if a certain url can be reached via a dd-wrt router
#
# The two input arguments are:
# ${1} login name to router running dd-wrt, e.g. root@192.168.1.1
# ${2} check url, e.g. http://google.com

# set default values
REMOTE=${1:-192.168.1.1}
URL=${2:-http://www.google.com}
SSH_TIMEOUT=${3:-8}

# nagios expects one of the following return values
NAG_OK=0
NAG_WARN=1
NAG_CRIT=2
NAG_UNKNOWN=3

ssh -q -o ConnectTimeout=${SSH_TIMEOUT} -t root@${REMOTE} wget -q ${URL} -O- > /dev/null
if [ $? -eq 0 ]; then
  echo -n "OK"
  EX=$NAG_OK
else
  echo -n "CRITICAL"
  EX=$NAG_CRIT
fi
echo " - ${URL} via ${REMOTE}"

exit $EX
